id: P64EA9241
initial_creation_type: ocr
source_metadata:
  volumes:
    172de56d01d3412f85884a907400c7fc:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: རྡོ་རྗེ་དྲིལ་ཐབས་ཀྱི་མཆོད་པའི་ཐབས་ཀྱི་རིམ་པ།
      total_pages: 2043
      volume_number: 13
